- searchview/src/main/java/com/lapism/searchview/SearchView.java
- searchview/src/main/res/layout/search_view.xml
There's no need for SearchView to extend RelativeLayout, FrameLayout should do it. Also, the inflated layout can be optimized by merging (see http://android-developers.blogspot.ro/2009/03/android-layout-tricks-3-optimize-by.html)
> Optimized layout hierarchy

- searchview/src/main/java/com/lapism/searchview/SearchAnimator.java
- searchview/src/main/java/com/lapism/searchview/SearchView.java
Fixed issue with start & end points of reveal animation for SearchView
> Fixed issue with start & end points of reveal animation for SearchView

- searchview/src/main/java/com/lapism/searchview/SearchView.java
Fixed bug with visibility of CardView in SearchView when we use showSearch(false) (without animation)
> Fixed bug with visibility of CardView in SearchView

- build.gradle
- searchview/src/main/java/com/lapism/searchview/SearchItem.java
Pretty straightforward. I used TextUtils to write CharSequence to parcel. I don't think there's another/better alternative.
> SearchItem implements Parcelable

- sample/src/main/java/com/lapism/searchview/sample/ToolbarActivity.java
- searchview/src/main/java/com/lapism/searchview/view/SearchView.java
Hello,
I found it interesting to implement an action in the menu SearchView hamburger, I hope you will enjoy it.
Regards,
> implement action click in hamburger menu icon

- searchview/src/main/java/com/lapism/searchview/adapter/SearchAdapter.java
I think that some getters for the lists will be handy for the developers that want to customize the behavior of the adapter.
In my case, trying to add custom filtering.
> added getters for lists (handy for customizing the adapter)

- searchview/src/main/java/com/lapism/searchview/SearchView.java
This fixes
`The following classes could not be instantiated: - com.lapism.searchview.SearchView`
error in the Layout editor
> User isInEditMode() in show/hideKeyboard()

- gradle.properties
- searchview/src/main/java/com/lapism/searchview/SearchAnimator.java
- searchview/src/main/java/com/lapism/searchview/SearchView.java
- searchview/src/main/res/drawable/search_ic_arrow_back_black_24dp.xml
- searchview/src/main/res/values/attrs.xml
Fixed Reveal animation direction for RTL languages
Fixed Back arrow key for RTL languages
Added Toolbar with Back key version (Useful for result page)
> Added RTL languages support (Correct Reveal animation and Back key)

- searchview/src/main/java/com/lapism/searchview/SearchView.java
- searchview/src/main/res/drawable-ldrtl/search_ic_arrow_back_black_24dp.xml
I forgot to add the icon in my previous pull request.
I also fixed the error in editor when voice is true
> Added RTL back icon

- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/lapism/searchview/sample/activity/MenuItemActivity.java
- sample/src/main/java/com/lapism/searchview/sample/activity/ToggleActivity.java
- sample/src/main/java/com/lapism/searchview/sample/base/BaseActivity.java
- sample/src/main/res/layout/activity_toggle.xml
- sample/src/main/res/menu/nav_items.xml
- sample/src/main/res/values/strings.xml
- searchview/src/main/java/com/lapism/searchview/SearchView.java
As stated at issue #108, I've implemented this fix for making sure the search component is displayed after switching from VERSION_MENU_ITEM to either VERSION_TOOLBAR or VERSION_TOOLBAR_ICON.
I've also updated the sample app with an working example.
> Fix for issue #108

- searchview/src/main/java/com/lapism/searchview/SearchAnimator.java
- searchview/src/main/java/com/lapism/searchview/SearchView.java
> Add "should clear" check to callback animations

- searchview/src/main/java/com/lapism/searchview/SearchView.java
Attributes were configurable through XML, but not through SearchView instance.
> Add setters/getters for mShouldClearOnClose and mShouldClearOnOpen attributes

- sample/src/main/java/com/lapism/searchview/sample/activity/MenuItemActivity.java
- sample/src/main/java/com/lapism/searchview/sample/activity/ToggleActivity.java
- sample/src/main/java/com/lapism/searchview/sample/activity/ToolbarActivity.java
- sample/src/main/java/com/lapism/searchview/sample/base/BaseActivity.java
> Fix menu item highlighting

- searchview/src/main/java/com/lapism/searchview/SearchView.java
> Hint is kept after search view is cleaned

- searchview/src/main/java/com/lapism/searchview/SearchView.java
mSearchAdapter  is not necessary
> Remove duplicate adapter.

- searchview/src/main/java/com/lapism/searchview/SearchAdapter.java
- searchview/src/main/java/com/lapism/searchview/SearchHistoryTable.java
- searchview/src/main/res/values-land/dimens.xml
fix search height landscape
searched query update _id
> pull request

- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/lapism/searchview/sample/activity/FiltersActivity.java
- sample/src/main/java/com/lapism/searchview/sample/activity/HistoryToggleActivity.java
- sample/src/main/java/com/lapism/searchview/sample/activity/ToggleActivity.java
- sample/src/main/java/com/lapism/searchview/sample/activity/ToolbarActivity.java
- sample/src/main/java/com/lapism/searchview/sample/base/BaseActivity.java
- sample/src/main/res/menu/nav_items.xml
- sample/src/main/res/values/strings.xml
- searchview/src/main/java/com/lapism/searchview/SearchAdapter.java
- searchview/src/main/java/com/lapism/searchview/SearchHistoryDatabase.java
- searchview/src/main/java/com/lapism/searchview/SearchHistoryTable.java
- searchview/src/main/java/com/lapism/searchview/SearchView.java
fix filters on suggestion click (my bad)
fix crash (trying to open a closed database instance)
databaseKey for using searchView in multiple contexts (issue #150)
> fixes and issue #150

- sample/src/main/java/com/lapism/searchview/sample/base/BaseActivity.java
- searchview/src/main/java/com/lapism/searchview/SearchView.java
- searchview/src/main/res/layout/search_view.xml
> fix crash when scrolling recycler view

- searchview/src/main/java/com/lapism/searchview/SearchView.java
- searchview/src/main/res/layout/search_view.xml
- searchview/src/main/res/values/dimens.xml
This PR adds support for showing an indeterminate progress spinner in the SearchView (like in GoogleMaps app).
Introduced SearchView methods:
- showProgress()
- hideProgress()
- isShowingProgress()
> added possibility to show an indeterminate progressBar

- searchview/src/main/res/values/attrs.xml
> Fixed search_height attribute format

- searchview/src/main/java/com/lapism/searchview/SearchAdapter.java
Checks the custom list before querying the default database.
> Allows to show all suggestions if using custom List<SearchItem> and the key is empty.

- searchview/src/main/java/com/lapism/searchview/SearchAdapter.java
Avoid using notifyDataSetChanged() because of the android issue
> Fixes #165

- searchview/src/main/java/com/lapism/searchview/SearchFilter.java
- searchview/src/main/java/com/lapism/searchview/SearchView.java
Made SearchFilter parcelable.
Added String tagId field to SearchFilter.
Added getSearchFilters() method to SearchView
> Method to get search filters

- searchview/src/main/java/com/lapism/searchview/FlowLayout.java
- searchview/src/main/java/com/lapism/searchview/SearchView.java
- searchview/src/main/res/layout/search_view.xml
- searchview/src/main/res/values/attrs.xml
Solves issue #222 
Used library from blazsolar: https://github.com/blazsolar/FlowLayout/blob/develop/FlowLayout/src/main/java/com/wefika/flowlayout/FlowLayout.java
> Fix bug when displaying a lot of filters

- searchview/src/main/java/com/lapism/searchview/SearchView.java
> fix bug in setting mIsSearchOpen #issue237

- searchview/src/main/java/com/lapism/searchview/SearchAdapter.java
Please add this to future release, very useful feature to handle suggestions if you getting back result you were put to adapter. I also created new interface to backward compatibility and 2 new methods to add new callback
> SearchItem in adapter click callback

- README.md
Search items use ID search_text since 5.0.0alpha5
> Fix search item ID

- src/main/java/com/lapism/searchview/SearchAdapter.java
- src/main/java/com/lapism/searchview/SearchView.java
I have found a neater way to show the suggestions properly along with the divider at the same time. I used `Filter.FilterListener` to listen for `onFilterComplete()`. That's a much better approach to show the suggestions at the correct time. Other minor edits include extra line removals and using switch statement instead of if statement when possible as switch statement is cleaner to use.
> Fixed mViewDivider not showing

- src/main/java/com/lapism/searchview/SearchView.java
I have tested it, and no crash longer exists.
> Fixed issue #294

- README.md
- src/main/java/com/lapism/searchview/SearchAnimator.java
I tested everything, and it works now.
> Fixed issue #318
